spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
# Set the default logging level to INFO
logging.level.org.springframework.web=INFO
logging.level.com.example.incidentportal=DEBUG
#logging.level.org.hibernate.SQL=DEBUG  # Logs SQL queries
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE  # Logs bind parameters
logging.level.org.hibernate.type.descriptor.sql.basicbinder=DEBUG
